all:
  children:
    gateways:
      hosts:
        tango.local:
          ansible_host: 192.168.1.36
    metricsservers:
      hosts:
        mate.local:
          ansible_host: 192.168.1.44
    caddyservers:
      hosts:
        tango.local:
          CaddyfileTemplateSrc: CaddyfileGateway.j2
        mate.local:
          CaddyfileTemplateSrc: CaddyfileMetricsServer.j2

  vars:
    ansible_user: root
    ansible_python_interpreter: auto_silent

