{
 "title": "Caddy Metrics",
 "description": "Dashboard set for Caddy proxy",
 "tags": [ "caddy" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values({__name__=~\"^caddy.*\",handler=~\".*\"},handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP(S) requests total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP(S) errors total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\"}[5m])))"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}