{
 "title": "Speedtest",
 "description": "Dashboard for https://github.com/nlamirault/speedtest_exporter",
 "tags": [
  "speedtest",
  "network"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_download" }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_upload" }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_ping" }
   ]
  },
  {
   "title": "Speedtest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "speedtest_download", "legendFormat": "Download" },
    { "expr": "speedtest_upload", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Ping time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "Ping" }
   ]
  }
 ]
}